//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.THERAPY = new HashSet<THERAPY>();
        }
    
        public int Id { get; set; }
        public string Fullname { get; set; }
        public System.DateTime Dateofbirth { get; set; }
        public int Idstatus { get; set; }
        public int Idposition { get; set; }
    
        public virtual POSITIONTABLE POSITIONTABLE { get; set; }
        public virtual STATUSTABLE STATUSTABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THERAPY> THERAPY { get; set; }
    }
}
