//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THERAPY
    {
        public int Id { get; set; }
        public string Diagnose { get; set; }
        public string Ambulatory { get; set; }
        public int Disability { get; set; }
        public System.DateTime Begintherapy { get; set; }
        public int Idpatient { get; set; }
        public int Iddoctor { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
