CREATE DATABASE [HOSPITAL]
USE [HOSPITAL]
GO
CREATE TABLE [PATIENT](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Fullname]			NVARCHAR(30)						NOT NULL,
[Dateofbirth]		DATETIME							NOT NULL,
[Idstatus]			INT CONSTRAINT FK_PATIENT_IDSTATUS_STATUSTABLE_ID FOREIGN KEY REFERENCES [STATUSTABLE] ([ID]) NOT NULL,
[Idposition]		INT CONSTRAINT FK_DOCTOR_IDPOSITION_POSITIONTABLE_ID FOREIGN KEY REFERENCES [POSITIONTABLE] ([ID]) NOT NULL
)
GO
CREATE TABLE [STATUSTABLE](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Status]			NVARCHAR(20)						NOT NULL
)
GO
CREATE TABLE [POSITIONTABLE](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Position]			NVARCHAR(20)						NOT NULL
)
GO
CREATE TABLE [DOCTOR](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Doctorname]		NVARCHAR(30)						NOT NULL,
[Post]				NVARCHAR(20)						NOT NULL,
[Idskill]			INT CONSTRAINT FK_DOCTOR_IDSKILL_SKILLTABLE_ID FOREIGN KEY REFERENCES [SKILLTABLE] ([ID]) NOT NULL,
[Idspecialization]	INT CONSTRAINT FK_DOCTOR_IDSPECIALIZATION_SKILLTABLE_ID FOREIGN KEY REFERENCES [SPECIALIZATIONTABLE] ([ID]) NOT NULL
)
GO
CREATE TABLE [SKILLTABLE](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Skill]				NVARCHAR(20)						NOT NULL
)
GO
CREATE TABLE [SPECIALIZATIONTABLE](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Specialization]	NVARCHAR(20)						NOT NULL,
)
CREATE TABLE [THERAPY](
[Id]				INT PRIMARY KEY IDENTITY(0,1)		NOT NULL,
[Diagnose]			NVARCHAR(30)						NOT NULL,
[Ambulatory]		NVARCHAR(10)						NOT NULL,
[Disability]		INT									NOT NULL,
[Begintherapy]		DATETIME							NOT NULL,
[Idpatient]			INT CONSTRAINT FK_THERAPY_IDPATIENT_PATIENT_ID FOREIGN KEY REFERENCES [PATIENT] ([ID]) NOT NULL,
[Iddoctor]			INT CONSTRAINT FK_THERAPY_IDDOCTOR_DOCTOR_ID FOREIGN KEY REFERENCES [DOCTOR] ([ID]) NOT NULL
)
GO